<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXT9EWCx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXT9EWCx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXT9EWCx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXT9EWCx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXT9EWCx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XT9EWCx',
    'container.build_id' => '27d79c02',
    'container.build_time' => 1743146745,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXT9EWCx');
