<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxxH7Y2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxxH7Y2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxxH7Y2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxxH7Y2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVxxH7Y2\App_KernelDevDebugContainer([
    'container.build_hash' => 'VxxH7Y2',
    'container.build_id' => '3b62d80e',
    'container.build_time' => 1746037451,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxxH7Y2');
